### ISSUE TITLE
Remove measures intermediate files

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#106]
## measures files

As I understand it, the measures system automatically creates some output files which we possibly don't need to keep. Later versions of measures stream the data rather than writing it disk, but there seem to be quite a few projects that are still using a useful amount of disk space for these intermediate files. 

We currently estimate that we have about 2-3 months (i.e. August/September) before we completely exhaust the disk space on the TPP server, but it will be difficult to ask TPP for more disk space before November. These files are not the biggest contributor to the problem, but they may be low-hanging fruit, which (everything else being equal) would give us another 1-2 months of runway. 

The files look like:

```
output/input<alpha-num-underscore>_<YYYY_MM_DD>.<extension>
```

or suggested regex

```
input.*\d\d\d\d_\d\d_\d\d\..*
```

@madwort has been using a script based around this shell glob to try and assess the impact. 

```bash
tpp:/srv/high_privacy/workspaces/workspace1/output$ du -sbch input*20[12][7890123]-[0-9][0-9]-[0-9][0-9]\.*
```

The largest workspaces with this type of file include:

asthma_sro 133G
the_effects_of_covid-19_on_doac_prescribing 161G
qof-blood-pressure 109G
pincer-measures 92G
opioids_covid_research 89G

I estimate the total size of these files is up to 1TB. 

In order to feel confident deleting these files, I'd like to be more confident about my shell glob, maybe @evansd could review the list of files to be deleted?

(originally at https://github.com/opensafely-core/sysadmin/issues/103#issuecomment-1573369799 )

**Comment by madwort** [comment]
Seems I may have misunderstood - this may be more of a potential improvement for future studies, we may not be able to reclaim this space for current & archived studies. Needs wider discussion.

**Comment by lucyb** [comment]
That's a shame. Do you know if it's a thing that's been fixed in ehrQL?

Given that we've since found some more space, it's probably worth closing this ticket now, I think?

**Comment by madwort** [comment]
possible quick discussion at the team meeting on 8th June, otherwise this ticket will be closed as "WILLNOTFIX"

**Comment by madwort** [comment]
yep, this will go away with the switch to ehrql, no action for the current workspaces.
