### ISSUE TITLE
[Review March 2024] Reduce disk usage of largest workspaces

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#107]
These two workspaces are both using over 1TB, can they be reduced?

https://jobs.opensafely.org/staff/workspaces/post-covid-vaccinated/ - 1.1TB
https://jobs.opensafely.org/staff/workspaces/post-covid-pre-vaccinated-cardiovascular/ - 1.6TB

@madwort to liaise with co-pilot Alex Walker https://jobs.opensafely.org/staff/projects/investigating-events-following-sars-cov-2-infection/ 

I think they contain lots of csv files, maybe we can switch them to csv.gz - will ask @bloodearnest for advice when he's back from holiday as he's done this elsewhere

**Comment by bloodearnest** [comment]
The plan with bristol for these was to switch to new workspace using .csv.gz, and archive these.

We should probably check with Venexia if these can be archived.

**Comment by madwort** [comment]
ok asked Venexia on slack

**Comment by madwort** [comment]
> Both of these repositories relate to a paper that is under review so we are not actively using them but we are expecting to have to use them in response to reviewers' feedback. Is it possible to temporarily archive them and then unarchive them if we need to do further work? These are some of our oldest repos hence the less than ideal desk space usage...

**Comment by madwort** [comment]
so, the upshot seems to be - it's probably not worth the trouble of trying to archive them now & inarchive them later, as it's the later when we'd be hitting a crunch point anyway. But it might be that with some other work we can buy enough time so that the crunch point comes after these papers can be archived.

**Comment by lucyb** [comment]
I think that sounds sensible. Can you put in a slackbot reminder to send a message into #team-pipeline in September to ask again about archiving them so we don't forget, please?

**Comment by madwort** [comment]
reminder set for 6th Sept

**Comment by madwort** [comment]
venexia has given the go-ahead to archive these, @madwort to do this 11th Sept 2023

**Comment by lucyb** [comment]
I chased this up yesterday and [Alex responded](https://bennettoxford.slack.com/archives/C028EJH752A/p1697533179981559?thread_ts=1693994047.731579&cid=C028EJH752A) to say that Bristol are working on the reviewer feedback at the moment. They're hoping to return it soon and to get a decision on the paper by Christmas. I've set another reminder for mid-Dec.

**Comment by madwort** [comment]
just bumped my reminder to check on this from this week to 13 Dec :(

**Comment by madwort** [comment]
[sent Alex a chaser](https://bennettoxford.slack.com/archives/C028EJH752A/p1702465947293329?thread_ts=1693994047.731579&cid=C028EJH752A) on slack

**Comment by madwort** [comment]
> "Afraid not. Cardiovascular is still under review!"

punted to March 2024

**Comment by madwort** [comment]
[Venexia says:](https://bennettoxford.slack.com/archives/C028EJH752A/p1712140783463509?thread_ts=1693994047.731579&cid=C028EJH752A)
> Cardiovascular is done - will archive now

**Comment by madwort** [comment]
1.8T for cardio, 1.2T for vaccinated in `/srv/high_privacy/workspaces/`

**Comment by madwort** [comment]
cardio still running at 14:12, logging out of TPP shortly, will check in later

**Comment by madwort** [comment]
cardio is archived! we now have 3.3GB free, up from 1.4GB! 🎉

**Comment by madwort** [comment]
started archiving `post-covid-vaccinated`

**Comment by madwort** [comment]
archiving completed & workspace deleted. all done! free disk is now 4.6TB 🎉 🎉 🎉 🎉 🎉 🎉
