### ISSUE TITLE
Investigate alternatives to Freshping

### ISSUE THREAD

**Issue by tomodwyer** [opensafely-core/sysadmin#119]
We use Freshping to monitor the availability of some of our systems, including Job Server. We use their free service.

Recently this message appeared on the [Freshping website](https://www.freshworks.com/website-monitoring/):

> We want to inform you that we will not be accepting new sign-ups for Freshping, effective immediately. As a result, support for our Freshworks free plan customers will be suspended. We apologize for any inconvenience this may cause.
>
> We will continue to support our paid customers and appreciate your understanding during this time. Please reach out to support support@freshping.io for any questions.

It's hard to tell from this if the free service will stop working and when, but I think we have to assume that it will disappear at any moment. So far as we know, we do have the option to just start paying for the service we currently use. But one possible reason for this change is that the whole business might be in trouble, so we need to consider having to find an alternative.

This ticket covers doing a quick assessment of the options available to us and coming up with a recommendation of one or two good possibilities.

**Comment by tomodwyer** [comment]
Options:

- https://pulsetic.com/
- https://www.checklyhq.com/
- https://www.uptrends.com/

**Comment by lucyb** [comment]
Another reason for doing this work is that freshping is frequently sending false alerts into the tech support channel. It's very distracting for anyone on tech support and means we're likely to miss real alerts. I think this is why EMIS was unreachable for over a day before we noticed when we did the run_command work.

**Comment by tomodwyer** [comment]
## Feature comparison

|                                   | Pulsetic  | Checkly | Uptrends | Oh Dear |
| --------------------------------- | --------- | ------- | -------- | ------- |
| Price (monthly)                   | £32 ($39) |         |          |         |
| Monitor count                     | 200       |         |          |         |
| Check intervals                   | 30 secs   |         |          |         |
| Users                             | 200       |         |          |         |
| Status pages (with custom domain) | ✅        |         |          |         |
| Status page subscribers           | 5000      |         |          |         |
| Maintenance windows               | ❌        |         |          |         |

---

## [Pulsetic](https://pulsetic.com/)

### Pros

1. Really simple UI
1. b
1. c

### Cons

1. a
1. b
1. c

### Bonus features

- Status badges for repos

---

## [Checkly](https://www.checklyhq.com/)

### Pros

1. a
1. b
1. c

### Cons

1. a
1. b
1. c

### Bonus features

- a
- b
- c

---

## [Uptrends](https://www.uptrends.com/)

### Pros

1. a
1. b
1. c

### Cons

1. a
1. b
1. c

### Bonus features

- a
- b
- b

---

## [Oh Dear](https://ohdear.app/)

### Pros

1. a
1. b
1. c

### Cons

1. a
1. b
1. c

### Bonus features

- a
- b
- c

---

## Conclusion

abc

**Comment by bloodearnest** [comment]
No Pagerduty?

It's really quite good, IME

**Comment by tomodwyer** [comment]
@bloodearnest Yeah I tried to avoid anything which was "pay per user" as we don't have a defined number of users to estimate costs for, especially with our fluid tech support rota.

**Comment by sebbacon** [comment]
None of these sound particularly great, do they? Loathe though I am to self-host in genera, is it worth considering self-hosting prometheus or similar, given we're already self-hosting grafana?

Given we've found freshping flaky anyway, it feels like the risk of having a single point of failure in a monitoring system that we manage isn't necessarily a killer one.
