### ISSUE TITLE
Migrate infrastructure repositories to opensafely-core organisation

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#12]
We want to move the open source infra projects (e.g. job-runner, job-server, output-publisher, opensafely-cli, etc) into a separate organisation, for a few reasons.

Firstly, it provides a clear security barrier between research studies and operational code. Currently, this is managed through Github's teams via manage-github.py script, but it's not very clean, and increasingly a maintain burden.  Moving sensitive repos to an external org means we can differentiate researchers and developers more clearly.

Secondly, it improves our researcher onboarding capabilities. We can more easily add members to opensafely org, and split them into teams with different repo access. 

Thirdly, it makes the `opensafely` organisation all about the *users* of opensafely, containing just studies and supporting documentation, and the `opensafely-core` organisation all about the *developers* of the platform.

Fourthly, it makes things simpler. It reduces the the number of repos in the opensafely org,  researchers are less likely to be confused by infra repos, some things are simpler to implement - e.g. updating all repos, or job-server repo selection logic, as it doesn't have to filter out the infra repos.

**Comment by bloodearnest** [comment]
repositories to be moved

*

**Comment by bloodearnest** [comment]
Migration questions

 - do we want to move s/master/main at the same time?
 - should we still publish the github images under the opensafely org name, because a) no migration needed b) its user facing anyway?

**Comment by bloodearnest** [comment]
Migration TODOs (WIP)

- update job-runner and output-publisher checkouts in TPP and EMIS servers
- update developers local repos
- update links in https://opensafely.org/code/ and probably other documentation

**Comment by madwort** [comment]
> * do we want to move s/master/main at the same time?

looking like a hard no

**Comment by bloodearnest** [comment]
> > * do we want to move s/master/main at the same time?
> 
> looking like a hard no

Yeah, lets make the delta as small as possible

**Comment by madwort** [comment]
> update developers local repos 

`sed -i -e 's/github.com:opensafely/github.com:opensafely-core/' .git/config`
or
`sed -i -e 's?https://github.com/opensafely?https://github.com/opensafely-core?' .git/config`

**Comment by madwort** [comment]
@bloodearnest just came across this old ticket - all done I think
