### ISSUE TITLE
SPIKE Can we setup self-hosted Grafana to use SSO?

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#145]
From a cursory read, it looks like we can setup Grafana to use SSO, so that we could use our ebmdatalab Google account. This would make administering access much easier and make the self-hosted option much more attractive.

**Comment by madwort** [comment]
SAML authentication requires the `grafana-enterprise` Docker image https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/saml-ui/
