### ISSUE TITLE
SPIKE How do we setup self-hosted Grafana to use a postgres db?

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#146]
By default, Grafana uses a sqlite db for storing its data. This works great while testing, but in production we should use something else. 

Using postgres as our database would mean our dokku webservers don't hold any state and would give us automatic backups, as our Digital Ocean postgres cluster already has backups set.

* What are the settings we need to use to enable Grafana to use postgres?
* Are these settings that can be passed in as env vars when we're using Dokku?

**Comment by madwort** [comment]
I think this is just the block https://github.com/opensafely-core/job-server/pull/3578/files#diff-89fafc265c1fa601cf2364b20be83308031335fda9467fcf3249d5ec1c0c8172R18-R23

I think we can pass these in with `dokku config:set` - see [environment variables](https://dokku.com/docs/configuration/environment-variables/)

**Comment by madwort** [comment]
Nb. I think Grafana would also want to persist some files to disk, but in my local Grafana I've been experimenting with, they don't seem to contain much of value. 


![Image](https://github.com/opensafely-core/sysadmin/assets/2082895/49dc45bc-0c30-46b7-b245-8340a6060832)

**Comment by lucyb** [comment]
I think this is done and working now, so can be closed.
