### ISSUE TITLE
Move job-server to dokku2

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#18]
* `dokku$ dokku maintenance job-server on`
* verify the `dokku` site is broken
* final copy of sqlite file to dokku2
  * `dokku$ scp /var/lib/dokku/data/storage/job-server/db.sqlite3 tom@dokku2.ebmdatalab.net:~/job-server-db.sqlite3`
  * `dokku2$ sudo cp job-server-db.sqlite3 /var/lib/dokku/data/storage/job-server/db.sqlite3`
* remove `dev.` prefix from domain on dokku2 & switch sentry logname from dev to prod
* `dokku2$ sudo dokku config:set job-server BASE_URL=https://jobs.opensafely.org`  (this updates `ALLOWED_HOSTS` )
* switch DNS
* …wait… :crossed_fingers:
* `dokku2$ sudo dokku letsencrypt job-server`  to pick-up new domain
* everything works great :tada:

**Comment by madwort** [comment]
Everything seems to be working - follow-up task: https://github.com/opensafely-core/sysadmin/issues/19

**Comment by madwort** [comment]
needs this merging https://github.com/opensafely-core/job-server/pull/423

**Comment by ghickman** [comment]
Merged and deployed successfully 🎉  Thanks for all your help on this Tom!
