### ISSUE TITLE
Clean-up deployment of opensafely/documentation

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#24]
We currently deploy to both github-pages *and* readthdocs - we should choose one (or a third alternative) and remove the other(s). See also https://github.com/opensafely/documentation/pull/228

**Comment by StevenMaude** [comment]
From tech team meeting, it sounds like "not GitHub Pages". Probably the quick fix there is remove deploy workflow to eliminate the ambiguity of where the deployment is; opensafely/documentation#231.

@tomodwyer might also have opinions about what we choose.

**Comment by madwort** [comment]
workflow removed & github pages disabled (by deleting the `gh-pages` branch)
