### ISSUE TITLE
EPIC Better system degradation monitoring

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#33]
GOAL: Improve our responsiveness to system problems so that we don’t rely on researchers reporting problems.

Tech support should be notified of important incidents with enough information to be able to investigate the problem.

Researchers should be provided with information about the current system status, so they don’t get frustrated and don’t need to contact tech support.

## Measure

- System availability trends over time
- Number of incidents
- Tech support burden (survey?)

## Solution

[https://bennettoxford.freshstatus.io/](https://bennettoxford.freshstatus.io/)

- Use this as a centralised place for updates
    - Send messages into slack when it’s updated
    - Users can sign up for email notifications for particular incidents
    - Automatically update when the database maintenance is taking place
    - Add future maintenance in when TPP notify us of scheduled maintenance windows
- Consider using names that represent the functions that researchers can perform, e.g releasing files, rather than application/tool names which might not mean as much
    - Be specific about the tasks that are affected - job submission, reviewing output, releasing files

**Comment by lucyb** [comment]
New issues:
1: Investigate feasibility of using freshstatus as a tool, including integrations

**Comment by lucyb** [comment]
Job runner should perform a generic db check
Each component should be able to report its status
Job runner (last seen), release hatch, db maintenance mode flags

**Comment by benbc** [comment]
I've moved this epic into the pipeline [here](https://docs.google.com/document/d/1tz6t0vD-oZ9wX3GfCaN3ul67A9rlJSgDfIs9hG_PFto/edit#).
