### ISSUE TITLE
Resource usage tracking and limiting

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#34]
GOAL: improve system stability and transparency by tracking and limiting resource usage.

- Provide developers with advance warnings of problems, so they can fix them before they affect researchers.
- Allow researchers to understand what resources their jobs can consume and when they are hitting limits, with enough information to allow them to take action.

## Measure

- Reduction in total resource exhaustion events server-wide
- Job queue time (should decrease slightly at busy times)
- Job run time (may increase at first)
- Job failures (likely to increase at first, but reduce as limits are tweaked and researchers adjust jobs)
- Tech support burden (survey?)

## Solution(s)

- Investigate common errors / interpret exit codes, to give users more information about failures
- Add TPP server resource usage metrics into Honeycomb
    - Use job-server as a proxy (dumb or smart?)
- Communicate job resource usage from the job-runner sqlite database out into Honeycomb
    - Use job-server as a proxy (dumb or smart?)
- Implement per-job resource limits
    - Configure these from job-server
    - Do this after metrics are in Honeycomb and users have been given more information about failures, so there’s enough information to make informed decisions

**Comment by benbc** [comment]
Closing in favour of pipeline item [here](https://docs.google.com/document/d/13lUPy05zrtERnsPUMe9v-JaEAoCu1w-BWs3_LvoVCIE/edit#).
