### ISSUE TITLE
Heartbeat call out to job server to know if Release Hatch is up or not

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#35]
We currently have multiple components that comprise a functioning backend. job-runner calls back to job-server regularly, and job-server tracks this heartbeat and uses it to track whether job-runner is up or not.

We should do the same for release-hatch, call out to job-server with a periodic heartbeat to let it know this instance of release hatch is up and running. This should be authenticated using the JOB_SERVER_TOKEN for that backend. 

Lack of recent contact from a release-hatch should trigger a status update procedure similar to lack of contact from job-runner.

(part of #33)

**Comment by bloodearnest** [comment]
I thought this was part of the monitoring work?

**Comment by lucyb** [comment]
In the interest of getting the monitoring work done (and moving that initiative out of development) we decided this wouldn't be part of this first version of the status page. If it all works as expected and people start using the status page regularly, then we can revisit this, as it would be a useful thing to include. Is that okay?
