### ISSUE TITLE
Link up freshstatus with Job Runner Last Seen Field

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#36]
To investigate the feasibility of using freshstatus as a tool, we'll get it to pick up the job runner last seen field from job server, report it on the dashboard and into a slack channel.

Test out the incident management process, by checking what happens when the last seen date exceeds a certain time. It should be possible to notify a slack channel that there's an incident and when the incident is resolved.

https://bennettoxford.freshstatus.io/

Parent: #33

**Comment by tomodwyer** [comment]
@ghickman No, we have set up the page as a test, but no automation work has been done.

You will probably need to set up Freshping to ping these endpoints, and then pass that information on to Freshstatus, which will be able to open/close/update incidents based on the ping status.

**Comment by ghickman** [comment]
I've set up TPP to drive the TTP database status on [our page](https://bennettoxford.freshstatus.io/).  I'll hold off adding any others until we decide if we like it or not.

**Comment by lucyb** [comment]
@ghickman is the TPP database status just the last seen field or does it cover this issue too? https://github.com/opensafely-core/sysadmin/issues/38

**Comment by ghickman** [comment]
@lucyb – still just the last seen field.  I still need to hook this up to the status page.  The automation I put already didn't update the status page during our recent downtime.

**Comment by ghickman** [comment]
This is blocked while the TPP backend is up.

Rather than rely on the (very!) rare occasions when we lose access to TPP we should find another view to test on.

One option is to add `/500` and `/404` views which test out the relevant pages with relevant status codes.

**Comment by ghickman** [comment]
Realised I could just point a new check at any known 404ing URL and it would work.

Going through the docs again I found that I'd missed setting up the webhook in _freshping_'s side to push changes to freshstatus so that explains why TPP being down a few weeks ago didn't trigger anything.

Testing now by editing the test check I added to freshping.

**Comment by ghickman** [comment]
Webhook worked with the dummy URL:

![](https://p198.p4.n0.cdn.getcloudapp.com/items/P8uQO0eZ/3349c7a9-91a8-4cb1-be99-dbedec0519d5.jpg?v=0ace61c975a535777ba52282475ee4ee)

**Comment by ghickman** [comment]
Testing this was a bit of pain so leaving this here for the next person working on it.

I created a new check in freshping pointing at `https://jobs.opensafely.org/TEST`, a known broken URL.  The integration between the two services uses webhooks so it push based.  You have to wait for freshping to mark that check as down (5+ minutes), confirm it's worked in statuspage, then edit it to `https://jobs.opensafely.org` (ie a working URL), wait for freshping to mark the check as back up (another 5+ minutes), and confirm it's worked in statuspage.

---

I've  [the rule driving the TPP service](https://bennettoxford.freshstatus.io/admin/settings/integration/freshping/5872/edit) in statusping back to the TPP check from freshping.
