### ISSUE TITLE
Upgrade honeycomb account (Pro edition?) [blocked]

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#39]
We are currently using Honeycomb's free plan, but are hitting our limit & probably need to upgrade at some point.

One feature that I think we want is Metrics - last time I looked I thought this was Enterprise-only, but looking again now it says "This feature is available as part of the [Honeycomb Enterprise and Pro plans](https://www.honeycomb.io/pricing/)."

Enterprise plans are only available after a chat with a customer service representative, which was tricky to organise, but we may now be able to get a Pro plan set up ourselves and be able to access what we need.

**Comment by madwort** [comment]
REQUIRED Pre-requisite: we currently have two teams "Datalab" and "Bennett Institute" - the first one was set up as Datalab, but in order to change the name on the invoice to the (new, correct) one, we have to set up a new team & migrate everything to the new team. We should set up billing on the new team & migrate new events to land there.

**Comment by madwort** [comment]
After discussion with @lucyb we realised that SSO is now *also* a Pro feature (rather than an Enterprise feature) so I think we can self-serve all that we need for now. So I've started the process of setting up billing with a view to switching off the free plan.

* [ ] get Hilary a honeycomb login
* [ ] get Hilary to get Finance to put in credit card details
* [ ] upgrade to "Pro"

**Comment by madwort** [comment]
@HilaryWin reports:

> Finance's credit card is no longer working. They claim that international companies' security settings haven't been updated to support UK requirements. Am having issues with Gandi and Google and they have suggested either we expense them or wait for invoices, which will cause delays.

**Comment by lucyb** [comment]
I've arranged a chat with a developer advocate at Honeycomb, who'll be able to talk us through whether we definitely need a pro account (probably?) and pass on our details to the relevant people, who'll also be able to tell us whether or not we can get a discount.

**Comment by lucyb** [comment]
I've chased Honeycomb and asked to be put in touch with a sales person

**Comment by madwort** [comment]
" I noticed your team is being throttled! I'd like to see Bennett Institute for Applied Data Science get to stretch its legs and see everything that Honeycomb can do. Here's a code to try Pro for a few months at 50% off:
YODI8UOW "

**Comment by madwort** [comment]
The person that I was originally in contact with was elizabethphillips@honeycomb.io

**Comment by lucyb** [comment]
Unfortunately, Elizabeth doesn't seem to work there any more, or at least her account's been disabled. I've just sent a reminder to Martin though.

**Comment by madwort** [comment]
> Unfortunately, Elizabeth doesn't seem to work there any more 

!!!

**Comment by madwort** [comment]
@lucyb just had a message out of the blue from Hilary saying that Finance have a new credit card & we could possibly now organise payments for this & get the upgrade to Pro. Shall I go ahead and organise that with Hilary? Is there a reason to wait until after any negotiations about a discount, or should we just unblock stuff?

**Comment by lucyb** [comment]
@madwort can it wait until next week without holding up any current work? I'll try contacting honeycomb one more time

**Comment by madwort** [comment]
yep that's fine

**Comment by madwort** [comment]
It's on the desk of Finance - Hilary to sit on the desk!

**Comment by HilaryWin** [comment]
Will prod 🙂



Hilary Winstanly

Personal Assistant to Professor Ben Goldacre

Administrator for the Bennett Institute
  Bennett Institute for Applied Data Science

  Nuffield Dept of Primary Care Health Sciences
  University of Oxford
  Radcliffe Observatory Quarter, Woodstock Road
  Oxford OX2 6GG
  ***@***.******@***.***> | bennett.ox.ac.uk<https://www.bennett.ox.ac.uk/>

[Bennett Institute for Applied Data Science logo] [Nuffield Department of Primary Care Health Sciences logo]  [University of Oxford logo]

I work part-time remotely Monday-Thursday for an equivalent of 3 days per week
Tuesdays: 9:00-17:00 | Mondays/Wednesdays/Thursdays: Regular access to emails
Fridays: Non-working day

________________________________
