### ISSUE TITLE
Honeycomb triggers for Pipeline team

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#40]
Use https://docs.honeycomb.io/working-with-your-data/triggers/ to alert pipeline team (via Slack?) when we cross interesting thresholds. This could be failing jobs, long-running jobs, or something else depending on team requirements.

**Comment by lucyb** [comment]
Correct me if I'm wrong, but I don't think we are planning to do this as part of the job-stats initiative. I suspect we will need to do this as issues come up as part of our day-to-day use of honeycomb though

**Comment by lucyb** [comment]
This came up recently during an incident with [slow running database queries](https://docs.google.com/document/d/13rmpZViQoiN4FwfEDuUs96QrQc3ay6XsJeyzWFKBbbc/edit#). It could be useful to provide this information to tech support now that we've got server metrics going into Honeycomb, as it could provide early warning of a problem.

**Comment by madwort** [comment]
For example - high CPU load, jobs that have been executing for a long time (inc. e.g. of type cohortextractor), & notify tech support.

**Comment by madwort** [comment]
high CPU load trigger created https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/triggers 

I think this is equivalent to notifying [#tech-support-channel](https://bennettoxford.slack.com/archives/C0270Q313H7) when [this graph](https://ui.honeycomb.io/bennett-institute-for-applied-data-science/environments/production/datasets/jobrunner-metrics/result/yqmbaGbCLV7/a/9CDqpWN3v7R/CPU-load-average?omitMissingValues) has a value over 95. I’m not convinced that this is going to do the right thing (it looks like a brief CPU spike when starting a job might be common enough that it will give us too many false positives), but we can see what happens? That graph has gone over 100 a couple of times - those may be the incidents that we want to catch.

**Comment by madwort** [comment]
After a bit of [discussion](https://bennettoxford.slack.com/archives/C03ELD5FEAU/p1669207744536339), 
we decided to implement a trigger to alert to Slack when metric `MIN(system.memory.usage.free)` falls below 2GB. This corresponds to Docker exhausting its memory allowance and beginning to kill jobs due to memory pressure (nb. Docker is configured so that the underlying system should not experience memory exhaustion). 

Trial alerts have successfully notified to Slack.

**Comment by madwort** [comment]
Free memory metric reduced to low level - after furthur investigation it was not strongly correlated with OOM kiilling. It should now only catch some kind of random catastrophic event.

**Comment by madwort** [comment]
Low disk space trigger created. Some current jobs require 1.3TB to finalise, so allow ourselves more than this when notifying.

**Comment by madwort** [comment]
added `system.memory.usage.free > 0` to the low mem trigger, hoping this will prevent it from firing when we have a short outage of honeycomb data (which we assume is due to transient network issues)

**Comment by madwort** [comment]
Added a "no events in jobrunner" trigger, to alert us if there's a problem with the otel-gateway setup

**Comment by madwort** [comment]
Closing this ticket. We have added a couple of triggers for (we think) useful things. We're still figuring out what might be useful, and some stuff will rely on forthcoming monitoring improvements (i.e. resource usage inside job containers). We should create more tickets for triggers as/when we have ideas, rather than having this long-running ticket.
