### ISSUE TITLE
Use SSO for honeycomb logins

### ISSUE THREAD

**Issue by madwort** [opensafely-core/sysadmin#44]
Use SSO to secure honeycomb logins, and also make it more widely available to the team. Follow-up from #39

**Comment by lucyb** [comment]
Is this now out of scope for the current job-stats initiative?

**Comment by madwort** [comment]
@lucyb only just saw your comments, I think once we have Honeycomb Pro, we will want to set this up to allow all devs to use the honeycomb interface.

**Comment by madwort** [comment]
done
