### ISSUE TITLE
Remove individual admin users from opensafely org repos

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#49]
Our policy currently only grants `maintain` privileges to researchers on study repos, as admin privileges are unsafe.

However, the person who creates the repo retains the default admin privileges that come with repo creation.

We should remove these vestigial roles, but it may need some careful communication with users.

**Comment by bloodearnest** [comment]
Maintain permsissions have been dropped for about ~2 weeks now, no issue so far.

I've spoken to the Bristol/Cambridge crew, they are happy to drop admin, so picking this up now.

**Comment by bloodearnest** [comment]
I have attempted to do this, but as this involved even more REST api calls, and we're already regularly hitting rate limits, I tried to tackle that issue first.

Currently, we make 4 or more API requests per repo. We have 220+ repos, and we run every 15mins, and hour, the ratelimit is 5000 per hour. This meant we were hitting limits regularly.

The plan was to use graphql to query all the info for the entire org in a few paginated requests, reducing the need for REST requests to write only. This should reduced our API calls from ~1000 to less than 100 per run. However, this proved incredibly complex and difficult to do, as the graphql API is very different to the REST api, with different naming, cardinality, and feature gaps. It doesn't seem like a good plan going forward.


Instead, we should probably find other ways to avoid hitting the limit. We could run less frequently. The only issue with that is that users currently cannot create a workspace from a repo until the script is run (which is the main reason we run it so often)

If we could alleviate that, then we can drop the frequency to 1/hour, and ignore ratelimits until they rear their head again

**Comment by lucyb** [comment]
I'm closing this issue for now, as we don't plan to do any more work on it at present (which having it in blocked implies).

**Comment by lucyb** [comment]
I'm closing this issue for now, as we don't plan to do any more work on it at present (which having it in blocked implies).

**Comment by bloodearnest** [comment]
I don't think we should close this issue.

George has now implemented the fix in https://github.com/opensafely-core/job-server/issues/1971 to mean the cron job can run less frequently, and I've altered the timing on my crontab to run 1/hour now.

This unblocks this ticket, as we now have rate limit to spare to implement the admin removal.

**Comment by bloodearnest** [comment]
Having users as admin means we cannot reliable enforce our policies.
