### ISSUE TITLE
Label repos that are pre-job-runner (aka legacy)

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#52]

**Comment by bloodearnest** [comment]
I have labelled these with the `legacy` topic, and collected them in this spreadsheet

https://docs.google.com/spreadsheets/d/1ziIHr2dsHR_xAjPKOWRehnauS7mKStECMpSZTTnPMp8/edit#gid=0

I think the next stage is for Amir follow up with researchers to make the them public.
