### ISSUE TITLE
Set up TPP email group

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#59]
Set up some form of shared email to use when communicating with TPP.

 - who should be on it?
 - shared inbox, or group with reply-to?
 - document the process

Would also be good to ask TPP if they can set up a group email for us to talk with.

**Comment by lucyb** [comment]
* Add the pipeline-team onto the list/group
* Simon will continue to respond for now. Everyone else can read and get up to speed on the sort of messages we receive, so a decision can be made in future about whether tech-support or another group should respond in future

**Comment by bloodearnest** [comment]
Done
