### ISSUE TITLE
Replace EOL debian dokku hosts

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/sysadmin#60]
dokku1 and dokku2 are currently on debian stretch, which is now EOL.

We need to move to something more recent.

We originally noted this earlier this year, and discussed waiting till Ubuntu 22.04.1 LTS (Aug 4th) was out.

Proposal:

 - start with a clean slate new VM rather than try upgrade in place
 - Ubuntu 22.04.1 LTS rather than debian[1]
 - find/write tooling to migrate dokku applications between hosts, iterate on new dokku1 replacement host until happy.
 - document and validate host level config:
    - docker logging config
    - [floating ip networking routes](https://github.com/ebmdatalab/sysadmin/blob/main/playbooks/servers.md)
    - cronjobs?
 - schedule downtime, switch DNS and floating IP address to new host.
 - repeat same process for dokku2 now we've done for dokku host.

As part of this, we should consider
 - using [tailscale ssh](https://tailscale.com/blog/tailscale-ssh/) for ssh rather than kissh
 - possibly scripting via ansible/packer or similar. Not sure its worth the effort.
 - setting up honeycomb host/docker metrics OOTB (assuming we pay honeycomb).
 - document the tooling for migrating dokku apps
 - appropriately sizing new VMs cpu/memory/disk for future growth

Note: this ticket does not consider smallweb1 or largeweb2 servers. :see_no_evil: :hear_no_evil: 

[1] arguments for ubuntu over debian:
 - longer support window (5 years versus ~3)
 - option for ubuntu advantage support (e.g. for audit compliance/tickboxing)
 - easier access to PPAs/snaps/livepatch if needed
 - more up to date with more active backporting and security patches.
 - [HWE kernels](https://ubuntu.com/kernel/lifecycle) are awesome
 - It's what most of us using linux are running, so familiarity and parity.
 - I have the phone numbers of key people if needed :D

**Comment by bloodearnest** [comment]
@madwort input welcome

**Comment by madwort** [comment]
> setting up honeycomb host/docker metrics OOTB (assuming we pay honeycomb).

definitely a separate ticket

**Comment by madwort** [comment]
dokku don't seem to mind breaking changes in version updates, so it might be worth thinking about how we can minimise moving parts - i.e. install the /same/ version of dokku as currently deployed on the new ubuntu 22 box & upgrade from there.

**Comment by bloodearnest** [comment]
Moved to gdoc: https://docs.google.com/document/d/15wHMcBYA4zlv2XWrZIwDgE1Ny9X1TYsmbpVwSuCtB6U/edit
