### ISSUE TITLE
Merge in opensafely-core/proxy and opensafely-core/backends

### ISSUE THREAD

**Issue by lucyb** [opensafely-core/sysadmin#99]
We could move these repos to sit under services/ in the opensafely-core/sysadmin repo:

- [ ] [opensafely-core/proxy](https://github.com/opensafely-core/proxy/) 
- [x] [opensafely-core/backends](https://github.com/opensafely-core/backends) 

This would reduce the number of repos we have to manage and maintain.

It would also potentially increase discoverability of those services, as currently people may not be aware those repos exist.

**Comment by madwort** [comment]
opensafely-core/backends was moved to ebmdatalab/sysadmin https://bennettoxford.slack.com/archives/C01SE1WB6AW/p1689944301727359?thread_ts=1689936655.781149&cid=C01SE1WB6AW

**Comment by madwort** [comment]
I'm not sure I'm convinced that it's worthwhile to merge the proxy into the sysadmin repo, but maybe we can discuss it at a pipeline team meeting?
